export const ALL_THEMES = [
  "Identité",
  "Habitudes",
  "Personnalité",
  "Amitié",
  "École et travail",
  "Technologie",
  "Jeux vidéo",
  "Musique",
  "Cinéma et séries",
  "Cuisine",
  "Voyage",
  "Sport",
  "Mode et style",
  "Animaux",
  "Maison",
  "Argent",
  "Réseaux sociaux",
  "Créativité",
  "Culture générale",
  "Aventure",
  "Situations improbables",
  "Futur",
  "Choix et goûts",
  "Talents",
  "Défis de groupe",
] as const;

export type ThemeName = (typeof ALL_THEMES)[number];
